# Generated by Django 4.0.4 on 2022-06-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
